include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    annotate_overrides: true
    hash_and_equals: true
    prefer_is_not_empty: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_child_properties_last: false
    use_build_context_synchronously: false
